#!/usr/bin/env node
/**
 * Bundle trim — the last step of the SESSION_6 cutover (see
 * src/lib/puzzleService.ts): with production serving from the DB, the
 * shipped JS must stop carrying unaired answers. Anyone can read the
 * public bundle; the full arrays made every future answer public.
 *
 * Emits src/data/generated/ (gitignored) with only AIRED days — today
 * included, so the DB-failure fallback still serves the correct daily:
 *  - nba-puzzles.ts  puzzles whose answer appears in the aired roster
 *  - nba-roster.ts   ROSTER sliced to today (the roster IS the schedule,
 *                    so future names are future answers)
 *  - nfl-puzzles.ts / mlb-puzzles.ts  release-order arrays sliced to
 *                    today; benched arrays are dropped entirely
 *  - nfl-roster.ts / mlb-roster.ts    emptied — the authoring wishlists
 *                    are not schedules, but authors work down them in
 *                    order, so shipping them predicts upcoming answers;
 *                    release-mode scheduling never reads them at runtime
 *
 * vite.config.ts remaps the authored modules to these files during
 * `vite build` ONLY — dev, validators, pipeline tooling, and the admin
 * app keep the full arrays (admin ships them too, but every admin URL
 * sits behind Vercel SSO). Runs inside `npm run build`, so every deploy
 * recomputes "aired" from that moment's ET date; the nightly rebuild
 * workflow keeps the cutoff fresh between content pushes.
 *
 * Day math mirrors src/game/storage.ts exactly (ET calendar date,
 * launch day = day 1); launch dates are parsed from the sport configs
 * rather than duplicated here.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const OUT_DIR = "src/data/generated";

// --- day math (mirror of storage.ts todayET / dayNumberForDate) ---------
const todayET = new Intl.DateTimeFormat("en-CA", {
  timeZone: "America/New_York",
  year: "numeric",
  month: "2-digit",
  day: "2-digit",
}).format(new Date());
const dateToUTC = (s) => {
  const [y, m, d] = s.split("-").map(Number);
  return Date.UTC(y, m - 1, d);
};
const dayNumber = (launch) =>
  Math.max(1, Math.round((dateToUTC(todayET) - dateToUTC(launch)) / 86_400_000) + 1);

const launchDate = (sportFile) => {
  const src = readFileSync(sportFile, "utf8");
  const m = src.match(/createStorage\("[^"]*",\s*"(\d{4}-\d{2}-\d{2})"\)/);
  if (!m) throw new Error(`no createStorage launch date in ${sportFile}`);
  return m[1];
};

// --- array extraction (same technique as validate-puzzles.mjs) ----------
function loadArray(path, name) {
  const src = readFileSync(path, "utf8").replace(/\r\n/g, "\n");
  const st = src.indexOf(`export const ${name}`);
  if (st < 0) throw new Error(`${name} not found in ${path}`);
  const open = src.indexOf("[", src.indexOf("=", src.indexOf("]", st)));
  let d = 0, e = -1;
  for (let i = open; i < src.length; i++) { if (src[i] === "[") d++; else if (src[i] === "]" && --d === 0) { e = i; break; } }
  return Function(`return (${src.slice(open, e + 1)});`)();
}

const rosterKey = (name) =>
  name.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase().trim();

// --- compute aired slices ----------------------------------------------
const nbaDay = dayNumber(launchDate("src/sports/nba.tsx"));
const nflDay = dayNumber(launchDate("src/sports/nfl.tsx"));
const mlbDay = dayNumber(launchDate("src/sports/mlb.tsx"));

const fullRoster = [...readFileSync("src/data/roster.ts", "utf8").matchAll(/^\s+"([^"]+)",/gm)].map((m) => m[1]);
const airedRoster = fullRoster.slice(0, nbaDay);
const airedKeys = new Set(airedRoster.map(rosterKey));

const nbaPuzzles = loadArray("src/data/puzzles.ts", "puzzles");
const airedNba = nbaPuzzles.filter((p) => airedKeys.has(rosterKey(p.answer)));

const nflPuzzles = loadArray("src/data/nfl/puzzles.ts", "nflPuzzles").slice(0, nflDay);
const mlbPuzzles = loadArray("src/data/mlb/puzzles.ts", "mlbPuzzles").slice(0, mlbDay);

// the cycling fallback indexes puzzles[(day-1) % dailyPool]; dailyPool is 5
for (const [label, arr] of [["nba", airedNba], ["nfl", nflPuzzles], ["mlb", mlbPuzzles]]) {
  if (arr.length < 5) throw new Error(`${label}: trimmed pool ${arr.length} < dailyPool 5`);
}

// --- emit ---------------------------------------------------------------
mkdirSync(OUT_DIR, { recursive: true });
const header = (what) =>
  `// GENERATED by pipeline/trim-unaired.mjs — ${what}, aired days only\n// (through ET ${todayET}). Do not edit; do not commit.\nimport type { Puzzle } from "../../game/types";\n`;

writeFileSync(`${OUT_DIR}/nba-puzzles.ts`, `${header("NBA pool")}export const puzzles: Puzzle[] = ${JSON.stringify(airedNba)};\n`);
writeFileSync(
  `${OUT_DIR}/nba-roster.ts`,
  `// GENERATED by pipeline/trim-unaired.mjs — roster through ET ${todayET}. Do not edit; do not commit.\nexport { rosterKey } from "../rosterKey";\nexport const ROSTER: string[] = ${JSON.stringify(airedRoster)};\n`
);
writeFileSync(`${OUT_DIR}/nfl-puzzles.ts`, `${header("NFL pool")}export const nflPuzzles: Puzzle[] = ${JSON.stringify(nflPuzzles)};\n`);
writeFileSync(`${OUT_DIR}/mlb-puzzles.ts`, `${header("MLB pool")}export const mlbPuzzles: Puzzle[] = ${JSON.stringify(mlbPuzzles)};\n`);
const stubRoster = (name) =>
  `// GENERATED by pipeline/trim-unaired.mjs — authoring wishlist, stripped from\n// production builds (it predicts upcoming answers; release scheduling never\n// reads it at runtime). Do not edit; do not commit.\nexport const ${name}: string[] = [];\n`;
writeFileSync(`${OUT_DIR}/nfl-roster.ts`, stubRoster("NFL_ROSTER"));
writeFileSync(`${OUT_DIR}/mlb-roster.ts`, stubRoster("MLB_ROSTER"));

console.log(
  `[trim] ET ${todayET} — nba day ${nbaDay}: ${airedNba.length}/${nbaPuzzles.length} puzzles, roster ${airedRoster.length}/${fullRoster.length}` +
  ` | nfl day ${nflDay}: ${nflPuzzles.length} | mlb day ${mlbDay}: ${mlbPuzzles.length}`
);
