-- Owner-only schedule administration.
--
-- The admin application uses the same publishable key as the game. Access is
-- granted only when BOTH conditions are true:
--   1. auth.uid() is present in public.admin_users; and
--   2. the current access token has Supabase's aal2 (verified MFA) claim.
--
-- Bootstrap is intentionally manual: after applying this migration, insert
-- the owner's existing auth.users UUID into public.admin_users from the SQL
-- editor. There is no client-callable path that can promote an account.

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

drop policy if exists "admin sees own allowlist entry" on public.admin_users;
create policy "admin sees own allowlist entry"
  on public.admin_users for select
  to authenticated
  using ((select auth.uid()) = user_id);

revoke all on public.admin_users from public, anon, authenticated;
grant select on public.admin_users to authenticated;

create or replace function public.is_schedule_admin()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select exists (
    select 1
    from public.admin_users
    where user_id = (select auth.uid())
  );
$$;

revoke execute on function public.is_schedule_admin() from public, anon;
grant execute on function public.is_schedule_admin() to authenticated;

-- A stable identity lets the browser reorder rows without sending puzzle JSON
-- back to the database. Existing rows receive sequence values automatically.
alter table public.scheduled_puzzles
  add column if not exists schedule_id bigint generated by default as identity;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'scheduled_puzzles_schedule_id_key'
      and conrelid = 'public.scheduled_puzzles'::regclass
  ) then
    alter table public.scheduled_puzzles
      add constraint scheduled_puzzles_schedule_id_key unique (schedule_id);
  end if;
end $$;

create table if not exists public.schedule_versions (
  sport text primary key check (sport in ('nba', 'nfl', 'mlb')),
  version bigint not null default 1 check (version >= 1),
  updated_at timestamptz not null default now()
);

insert into public.schedule_versions (sport)
values ('nba'), ('nfl'), ('mlb')
on conflict (sport) do nothing;

create table if not exists public.admin_schedule_audit (
  id bigint generated always as identity primary key,
  actor_user_id uuid not null references auth.users(id),
  sport text not null check (sport in ('nba', 'nfl', 'mlb')),
  old_order jsonb not null,
  new_order jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists admin_schedule_audit_sport_created_idx
  on public.admin_schedule_audit (sport, created_at desc);

alter table public.schedule_versions enable row level security;
alter table public.admin_schedule_audit enable row level security;

-- The base scheduler tables previously had RLS enabled with no client
-- policies. These policies preserve that default-deny behavior for everyone
-- except an allowlisted owner with a freshly MFA-verified session.
drop policy if exists "owner reads schedule" on public.scheduled_puzzles;
create policy "owner reads schedule"
  on public.scheduled_puzzles for select
  to authenticated
  using (
    (select auth.jwt()->>'aal') = 'aal2'
    and (select public.is_schedule_admin())
  );

drop policy if exists "owner inserts schedule" on public.scheduled_puzzles;
create policy "owner inserts schedule"
  on public.scheduled_puzzles for insert
  to authenticated
  with check (
    (select auth.jwt()->>'aal') = 'aal2'
    and (select public.is_schedule_admin())
  );

drop policy if exists "owner updates schedule" on public.scheduled_puzzles;
create policy "owner updates schedule"
  on public.scheduled_puzzles for update
  to authenticated
  using (
    (select auth.jwt()->>'aal') = 'aal2'
    and (select public.is_schedule_admin())
  )
  with check (
    (select auth.jwt()->>'aal') = 'aal2'
    and (select public.is_schedule_admin())
  );

drop policy if exists "owner deletes schedule" on public.scheduled_puzzles;
create policy "owner deletes schedule"
  on public.scheduled_puzzles for delete
  to authenticated
  using (
    (select auth.jwt()->>'aal') = 'aal2'
    and (select public.is_schedule_admin())
  );

drop policy if exists "owner reads priority queue" on public.priority_queue;
create policy "owner reads priority queue"
  on public.priority_queue for select
  to authenticated
  using (
    (select auth.jwt()->>'aal') = 'aal2'
    and (select public.is_schedule_admin())
  );

drop policy if exists "owner manages priority queue" on public.priority_queue;
create policy "owner manages priority queue"
  on public.priority_queue for all
  to authenticated
  using (
    (select auth.jwt()->>'aal') = 'aal2'
    and (select public.is_schedule_admin())
  )
  with check (
    (select auth.jwt()->>'aal') = 'aal2'
    and (select public.is_schedule_admin())
  );

drop policy if exists "owner reads schedule versions" on public.schedule_versions;
create policy "owner reads schedule versions"
  on public.schedule_versions for select
  to authenticated
  using (
    (select auth.jwt()->>'aal') = 'aal2'
    and (select public.is_schedule_admin())
  );

drop policy if exists "owner updates schedule versions" on public.schedule_versions;
create policy "owner updates schedule versions"
  on public.schedule_versions for update
  to authenticated
  using (
    (select auth.jwt()->>'aal') = 'aal2'
    and (select public.is_schedule_admin())
  )
  with check (
    (select auth.jwt()->>'aal') = 'aal2'
    and (select public.is_schedule_admin())
  );

drop policy if exists "owner reads schedule audit" on public.admin_schedule_audit;
create policy "owner reads schedule audit"
  on public.admin_schedule_audit for select
  to authenticated
  using (
    (select auth.jwt()->>'aal') = 'aal2'
    and (select public.is_schedule_admin())
  );

drop policy if exists "owner writes schedule audit" on public.admin_schedule_audit;
create policy "owner writes schedule audit"
  on public.admin_schedule_audit for insert
  to authenticated
  with check (
    actor_user_id = (select auth.uid())
    and (select auth.jwt()->>'aal') = 'aal2'
    and (select public.is_schedule_admin())
  );

revoke all on public.scheduled_puzzles from authenticated;
grant select, insert, update, delete on public.scheduled_puzzles to authenticated;
grant usage, select on sequence public.scheduled_puzzles_schedule_id_seq to authenticated;

revoke all on public.priority_queue from authenticated;
grant select, insert, update, delete on public.priority_queue to authenticated;

revoke all on public.schedule_versions from public, anon, authenticated;
grant select, update on public.schedule_versions to authenticated;

revoke all on public.admin_schedule_audit from public, anon, authenticated;
grant select, insert on public.admin_schedule_audit to authenticated;
grant usage, select on sequence public.admin_schedule_audit_id_seq to authenticated;

create or replace function public.admin_reorder_schedules(p_payload jsonb)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_sport text;
  v_expected_version bigint;
  v_actual_version bigint;
  v_ids bigint[];
  v_current_ids bigint[];
  v_before jsonb;
  v_after jsonb;
begin
  if (select auth.uid()) is null
     or not (select public.is_schedule_admin())
     or coalesce((select auth.jwt()->>'aal'), '') <> 'aal2' then
    raise exception 'admin MFA session required' using errcode = '42501';
  end if;

  if jsonb_typeof(p_payload) <> 'object'
     or p_payload = '{}'::jsonb then
    raise exception 'at least one sport schedule is required' using errcode = '22023';
  end if;

  if exists (
    select 1 from jsonb_object_keys(p_payload) as k(sport)
    where sport not in ('nba', 'nfl', 'mlb')
  ) then
    raise exception 'payload contains an invalid sport' using errcode = '22023';
  end if;

  -- Lock every affected sport in a consistent order. This prevents two open
  -- admin tabs from interleaving saves and makes version checks reliable.
  perform 1
  from public.schedule_versions
  where sport in (select jsonb_object_keys(p_payload))
  order by sport
  for update;

  for v_sport in
    select jsonb_object_keys(p_payload)
    order by 1
  loop
    if jsonb_typeof(p_payload -> v_sport -> 'scheduleIds') is distinct from 'array' then
      raise exception 'scheduleIds must be an array for %', v_sport using errcode = '22023';
    end if;

    v_expected_version := (p_payload -> v_sport ->> 'expectedVersion')::bigint;

    select version into strict v_actual_version
    from public.schedule_versions
    where sport = v_sport;

    if v_expected_version is distinct from v_actual_version then
      raise exception 'schedule changed since it was loaded for %', v_sport
        using errcode = '40001';
    end if;

    select coalesce(array_agg(value::bigint order by ordinality), '{}'::bigint[])
    into v_ids
    from jsonb_array_elements_text(p_payload -> v_sport -> 'scheduleIds')
      with ordinality as wanted(value, ordinality);

    select coalesce(array_agg(schedule_id order by day), '{}'::bigint[]),
           coalesce(
             jsonb_agg(
               jsonb_build_object('scheduleId', schedule_id, 'day', day, 'answer', answer)
               order by day
             ),
             '[]'::jsonb
           )
    into v_current_ids, v_before
    from public.scheduled_puzzles
    where sport = v_sport
      and not frozen
      and day > public.current_day(v_sport);

    if cardinality(v_ids) <> cardinality(v_current_ids)
       or (select array_agg(x order by x) from unnest(v_ids) as x)
          is distinct from
          (select array_agg(x order by x) from unnest(v_current_ids) as x) then
      raise exception 'schedule rows changed since they were loaded for %', v_sport
        using errcode = '40001';
    end if;

    if v_ids = v_current_ids then
      continue;
    end if;

    -- Delete and reinsert only unfrozen future rows inside this transaction.
    -- This avoids transient unique(sport, day) collisions while preserving
    -- every puzzle, its stable schedule_id, and its original day slots.
    with desired as (
      select value::bigint as schedule_id, ordinality
      from jsonb_array_elements_text(p_payload -> v_sport -> 'scheduleIds')
        with ordinality as wanted(value, ordinality)
    ),
    slots as (
      select day, row_number() over (order by day) as ordinality
      from public.scheduled_puzzles
      where sport = v_sport
        and not frozen
        and day > public.current_day(v_sport)
    ),
    moved as (
      delete from public.scheduled_puzzles
      where sport = v_sport
        and not frozen
        and day > public.current_day(v_sport)
      returning schedule_id, sport, answer, puzzle, source, status, frozen, generated_at
    )
    insert into public.scheduled_puzzles
      (schedule_id, sport, day, answer, puzzle, source, status, frozen, generated_at)
    select moved.schedule_id, moved.sport, slots.day, moved.answer, moved.puzzle,
           moved.source, moved.status, moved.frozen, moved.generated_at
    from moved
    join desired using (schedule_id)
    join slots using (ordinality);

    update public.schedule_versions
    set version = version + 1,
        updated_at = now()
    where sport = v_sport;

    select coalesce(
      jsonb_agg(
        jsonb_build_object('scheduleId', schedule_id, 'day', day, 'answer', answer)
        order by day
      ),
      '[]'::jsonb
    )
    into v_after
    from public.scheduled_puzzles
    where sport = v_sport
      and not frozen
      and day > public.current_day(v_sport);

    insert into public.admin_schedule_audit
      (actor_user_id, sport, old_order, new_order)
    values ((select auth.uid()), v_sport, v_before, v_after);
  end loop;

  return (
    select coalesce(jsonb_object_agg(sport, version), '{}'::jsonb)
    from public.schedule_versions
    where sport in (select jsonb_object_keys(p_payload))
  );
end;
$$;

revoke execute on function public.admin_reorder_schedules(jsonb) from public, anon;
grant execute on function public.admin_reorder_schedules(jsonb) to authenticated;

comment on function public.admin_reorder_schedules(jsonb) is
  'Atomically reorders unfrozen future puzzles for one or more sports; owner allowlist plus aal2 required.';
